name: Generate README

on:
  push:
    branches:
      - main # or your default branch, like 'master'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Generate README
        run: |
          echo "# Awesome LLM resources" > README.md
          echo "" >> README.md
          for folder in "Foundations" "FineTuning" "Axolotl"; do
            echo "## $folder" >> README.md
            echo "" >> README.md
            for file in $folder/*.md; do
              if [ -f "$file" ]; then
                cat "$file" >> README.md
                echo "" >> README.md
              fi
            done
          done

      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          git commit -m "Update README" -a || echo "No changes to commit"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
